name = "wikihour-base"
main = "src/index.js"
compatibility_date = "2024-04-03" # Required for RPC
compatibility_flags = ["nodejs_compat"]

# New way to serve the public folder
[assets]
directory = "./public"

[durable_objects]
bindings = [{name = "WIKI_STATS", class_name = "WikiStats"}]

[[migrations]]
tag = "v1"
new_classes = ["WikiStats"]

[dev]
local_protocol = "https"